# Generated by Django 5.0.3 on 2024-03-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyordersummary",
            name="total_amount",
            field=models.FloatField(default=0.0),
        ),
    ]
